const router = require("express").Router()
const productController = require("../controller/productController")
const productAttributeController = require("../controller/productAttributeController")
const productVariationController = require("../controller/productVariationController")
const middlewareController = require("../controller/middlewareController")
router.post('/add', middlewareController.verifyTokenAdmin, productController.addProduct)
router.post('/addAttribute', middlewareController.verifyTokenAdmin, productAttributeController.addProductAttribute)
router.post('/addVarable', middlewareController.verifyTokenAdmin, productVariationController.addProductVariation)
router.delete('/deleteProduct/:id', middlewareController.verifyTokenAdmin, productController.deleteProduct)
router.put('/updateProduct/:id', middlewareController.verifyTokenAdmin, productController.updateProduct)
router.get('/detailProduct/:id', productController.detailProduct)
router.get('/', productController.getAllProduct)
router.delete('/deleteProductAttribute/:id', middlewareController.verifyTokenAdmin, productAttributeController.deleteProductAttribute)
router.put('/updateProductAttribute/:id', middlewareController.verifyTokenAdmin, productAttributeController.updateProductAttribute)
router.get('/getProductAttribute/:id', productAttributeController.getProductAttribute)
router.get('/getAllProductAttribute', productAttributeController.getAllProductAttribute)
router.delete('/deleteProductVariation/:id', middlewareController.verifyTokenAdmin, productVariationController.deleteProductVariation)
router.put('updateProductVariation/:id', middlewareController.verifyTokenAdmin, productVariationController.updateProductVariations)
router.get('getProductVariations/:id', productVariationController.getProductVariations)
//router.get('productVariation/', productVariationController.)
module.exports = router